[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bit-set = "0.5.3"
gcd = "2.3.0"
num = "0.4.1"
rayon = "1.8.1"
regex = "1.10.3"
